[package]
name = "litt"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
sha2 = "0.10.8"
flate2 = "1.0.34"
chrono = "0.4.38"
